config/routes.rb
Forum::Application.routes.draw do
	devise_for :users

	resources :sections, shallow: true do
		resources :posts do
			resources :comments
		end
	end

	resources :users

	root :to => 'sections#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body

  belongs_to :user
  belongs_to :section
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @section = Section.find(params[:section_id])
    @posts = @section.posts

    respond_to do |format|
      format.html { redirect_to section_posts_url(@section) }
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @section = Section.find(params[:section_id])
    @post = @section.posts.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @section = Section.find(params[:section_id])
    @post = @section.posts.build(params[:post])
    respond_to do |format|
      if @post.save
        format.html { redirect_to ( @post), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @section = Section.find(params[:section_id])
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to section_posts_url(@section) }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@section, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :title %>
    <%= f.text_area :body %>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_update_form.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :title %>
    <%= f.text_area :body %>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'update_form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', section_posts_path(@post.section) %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= link_to 'Show', post_url(post) %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_section_post_path(@section) %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', section_posts_path(@section) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<% @post.comments.each do |comment| %>
	<p><%= comment.content %></p>
<% end %>

<%= render :partial => 'comments/form' %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', section_path(@post.section) %>